### PR TITLE
Gamification

### PR DESCRIPTION
**Pull request by joaquinvanschoren**
bugfixes and other improvements

### CODE REVIEW

**Comment by DraXus** [comment]
Nice to see that you're working on gamification :)

**Comment by joaquinvanschoren** [comment]
We've been working on it for a while :). Please let us know what you think.

**Comment by DraXus** [comment]
Is there any demo server I can check?

**Comment by DraXus** [comment]
Nevermind, I just found this: http://www.openml.org/guide#!gamification

Wow, great work guys. I really like the new changes, now it makes me want to achieve those badges! :)

And sorry, I know a commit is not the place for these types of comments :)

**Pull request merged**
